### PR TITLE
Fix filter dropdown

### LINKED ISSUE #96: Filter dropdown buggy
image

- Logic currently within `ProjectList.vue` (being merged in from `cart` branch)
- not properly unchecking filter items after selection

### PR DESCRIPTION
**Pull request by pettinarip**
- Fix #96 
- I've extracted the dropdown logic into its own component.
- I've created a new directive called `v-click-outside={callback}` that will handle all this logic there (and perhaps we can use it in other use cases as well).

TODO:
- [x] Display the compact version ~~when we are in md resolution (either with the Cart open and close)~~ always.
- [x] Check `TypeError: Cannot read property 'toLowerCase' of undefined` error happening in the preview version.
- [x] Keep the dropdown div with a fixed width to avoid that the content moves.

### CODE REVIEW

**Review by samajammin — CHANGES_REQUESTED** [review]
Nice - love the ClickOutside directive!

I'm still noticing a couple errors around the dropdown (that may have already existed) when I play with it on the preview deploy (https://deploy-preview-169--eth2clrfund.netlify.app/#/projects):
1. console error on selecting a category:
```
TypeError: Cannot read property 'toLowerCase' of undefined
```
2. The text content jumps on selection: https://share.getcloudapp.com/xQu7zvmx

Perhaps to prevent this we have a persistent div that is the same width as the "x" icon, so the alignment & width stay constant? Something along those lines... open to other approaches.

**Comment by pettinarip** [comment]
Thanks for the feedback.

> 1. console error on selecting a category:

Ok. I'll take a look at that.

> 2. The text content jumps on selection:

I noticed the same, your approach makes sense. Will do that.

File: vue-app/src/components/FilterDropdown.vue [hunk 1]
```diff
@@ -0,0 +1,176 @@
+<template>
+  <div class="category-filter" v-click-outside="closeDropdown">
+    <div
+      :class="{
+        'filter-btn': true,
+        'filter-btn-cart-closed':
+          !!$store.state.currentUser && !$store.state.showCartPanel,
+        'filter-btn-cart-open':
+          !!$store.state.currentUser && $store.state.showCartPanel,
```
Comment (pettinarip) [inline vue-app/src/components/FilterDropdown.vue]: @samajammin @wackerow do you remember the purpose of these classes? it is setting `width: auto` in md resolution sizes. I think that the idea is to make the Filter fill the complete space in md sizes. Look at this:

Cart is closed:
cart closed

Cart is open:
cart open

As you can see, when the Cart is closed, the Filter dropdown does not expand to fill all the space but when the Cart is opened it does. I guess we want to make it consistent.

Comment (pettinarip) [reply vue-app/src/components/FilterDropdown.vue]: As we discussed, I'll keep it with the compact version in both states.

**Comment by pettinarip** [comment]
> console error on selecting a category

@samajammin I looked into this issue and it is only happening in the Netlify preview env. Not in my local. Investigating a bit I found the problem. It filters the projects by category and some do not have a category so `project.category` is returning undefined and then it tries `toLowerCase()` that.

Good catch.

What I'm going to do is: if it tries to filter a project that does not have a category, then it won't show it.  Rephrasing, only show this type of project when no filter is selected.

File: vue-app/src/directives/ClickOutside.js [hunk 2]
```diff
@@ -0,0 +1,15 @@
+export default {
```
Comment (corwintines) [inline vue-app/src/directives/ClickOutside.js:1]: Very cool, learned something new from this!

File: vue-app/src/components/FilterDropdown.vue [hunk 3]
```diff
@@ -0,0 +1,162 @@
...
+    grid-template-columns: repeat(1, 4fr);
+    border: 1px solid $border-color;
+    border-radius: 0.75rem;
+    overflow: hidden;
+    justify-content: space-between;
+    width: 100%;
+    z-index: 99;
+    .category-btn {
+      display: grid;
+      place-items: center;
```
Comment (corwintines) [inline vue-app/src/components/FilterDropdown.vue]: Screen Shot 2021-06-24 at 3 25 31 PM
Screen Shot 2021-06-24 at 3 25 39 PM

Just wanted to show these side by side where we change the style of `place-items: center;` to `place-items: left;` in .category-button and see what you guys thought. Its a bit nit picky, just was looking at it in comparison after @pettinarip changes. I dont have a strong opinion, but the consistency of `place-items: left;` may be nice if .category-btn-selected has `justify-content: space-between;` as the style.

**Review by corwintines — APPROVED** [review]
This is great, just had a comment that the team might be interested in talking about, but its not blocking for this so approving. Good job, Pablo!

File: vue-app/src/components/FilterDropdown.vue (hunk 3 above)
Comment (pettinarip) [reply vue-app/src/components/FilterDropdown.vue]: True! I hadn't realized that. Yes, I agree that this should be left aligned.

Comment (pettinarip) [reply vue-app/src/components/FilterDropdown.vue]: @samajammin what do you think?

Comment (wackerow) [reply vue-app/src/components/FilterDropdown.vue]: Didn't even spot this at first, but good catch @corwintines. Given that the "selected" state displays much better left aligned (with the close button right aligned), I think having the "unselected" items default to left align makes more sense. 

Otherwise this all looks and functions great on my end! Nice job @pettinarip!

File: vue-app/src/components/FilterDropdown.vue (hunk 1 above)
Comment (wackerow) [reply vue-app/src/components/FilterDropdown.vue]: @pettinarip Sorry for delay in responding to this, but yeah `filter-btn-cart-open` and `filter-btn-cart-closed` are there to conditionally lay out the filter menu based on a combination of both screen width (media queries) and weather or not the cart panel is visible / open or closed `state.showCartPanel`. 

This was a work around since there was no easy way to do a "media query" for the parent container size. The layout of the main content shifts slightly depending if there is no user logged in (thus no cart at all), a user logged in with a closed cart (slight shift to accomodate cart button) and an open cart (biggest shift). Hope this helps clarify.

File: vue-app/src/components/FilterDropdown.vue (hunk 3 above)
Comment (samajammin) [reply vue-app/src/components/FilterDropdown.vue]: Agreed - let's display these categories left aligned.

**Review by samajammin — CHANGES_REQUESTED** [review]
Looks great! See 1 comment - let's update to left align the categories.

File: vue-app/src/components/FilterDropdown.vue (hunk 3 above)
Comment (pettinarip) [reply vue-app/src/components/FilterDropdown.vue]: Done!

File: vue-app/src/components/FilterDropdown.vue (hunk 1 above)
Comment (pettinarip) [reply vue-app/src/components/FilterDropdown.vue]: Thanks for the explanation. 

I have removed them. Now that we are showing the filter always in the compact version I think there is no need for these classes anymore.

**Review by corwintines — APPROVED** [review]

**Review by samajammin — APPROVED** [review]
🚀
