### PR TITLE
Fix cart indicator

### LINKED ISSUE #112: Cart indicator logic
Should only pulse when you add something to the cart. At the moment it pulses on load (initial render) and on the first item added to cart but not when the cart quantity increases.

Standard:
image

Pulse:
Image 2021-06-08 at 9 40 37 AM

When an item is added to cart, pulse animation should trigger. Look into action trigger as a way to toggle a class?

Question:
- should the cart indicator be persistent or should we hide it once you've looked at it like a notification? Decision for now: keep it persistent.

### PR DESCRIPTION
**Pull request by pettinarip**
Fix #112

### CODE REVIEW

File: vue-app/src/components/CartWidget.vue [hunk 1]
```diff
@@ -12,14 +12,15 @@
...
-        :class="[
-          cart.length + -0 ? 'circle pulse cart-indicator' : 'cart-indicator',
-        ]"
-        v-if="!$store.state.showCartPanel && isCartBadgeShown"
-      >
-        {{ cart.length }}
-      </div>
+      <transition name="pulse" mode="out-in">
+        <div
+          :key="cart.length"
```
Comment (pettinarip) [inline vue-app/src/components/CartWidget.vue:17]: Using `<transition>` whenever the `key` changes, it's going to execute the `pulse` animation. More on this here: https://vuejs.org/v2/guide/transitions.html#Transitioning-Between-Elements

**Review by samajammin — APPROVED** [review]
Nice!
