### PR TITLE
Fix partial contributions (without sending votes)

### LINKED ISSUE #212: Cart displays reallocation message before contribution is complete
https://www.notion.so/efdn/Cart-displays-reallocation-message-before-contribution-is-complete-3dd080d91a784677a5a6bb0183a54cf5

Noticed when testing a contribution that the reallocation displays prematurely (it displays after the 2nd of 3 txs):

Image 2021-07-21 at 2 44 21 PM

We should hide this until the user's contribution flow is complete to avoid confusion.

### PR DESCRIPTION
**Pull request by pettinarip**
Fixes #212 and #94

In this scenario, I have added the following:
- Added a new event (`Voted`) on the `FundingRound` to identify when a user has submitted the votes.
- Added a new boolean state on the root state: `hasVoted`, to know if a user has sent the votes or not.
- Based on that flag, we display proper UI in the Cart with a "Finish contribution" button to finish and send the missing votes to the round.
- This new UI is the same as the Reallocation UI except that we display a different submit button.
- The `ContributionModal` has been changed to be able to directly open in the final step (3), to submit the votes.

**Naming proposals are accepted** :) particularly around the `SET_HAS_VOTED` mutation name.

### CODE REVIEW

**Review by corwintines — APPROVED** [review]

File: vue-app/src/store/index.ts [hunk 1]
```diff
@@ -88,6 +90,7 @@ interface RootState {
   committedCart: CartItem[]
   contribution: BigNumber | null
   contributor: Contributor | null
+  hasVoted: boolean
```
Comment (samajammin) [inline vue-app/src/store/index.ts:93]: Would this make more sense to track this on `currentUser.hasVoted`?

Comment (samajammin) [reply vue-app/src/store/index.ts:93]: Although I suppose we already have a mix of top-level state related to the user, e.g. `contribution` 🤷‍♂️

File: vue-app/src/components/Cart.vue [hunk 2]
```diff
@@ -6,12 +6,22 @@
       <wallet-widget :isActionButton="true" />
     </div>
     <div v-else class="cart-container">
-      <div class="reallocation-message" v-if="$store.getters.canUserReallocate">
+      <div
+        class="reallocation-message"
+        v-if="$store.getters.canUserReallocate && $store.getters.hasUserVoted"
```
Comment (samajammin) [inline vue-app/src/components/Cart.vue:11]: Won't `hasUserVoted` always be true if `canUserReallocate` is true?

Comment (samajammin) [reply vue-app/src/components/Cart.vue:11]: If not, perhaps we should update `canUserReallocate` logic to ensure the user has already voted?

Comment (samajammin) [reply vue-app/src/components/Cart.vue:11]: I think so - a user must vote in order to finish their contribution. Before then I think `canUserReallocate` should be false.

File: vue-app/src/components/ContributionModal.vue [hunk 3]
```diff
@@ -118,10 +121,31 @@ export default class ContributionModal extends Vue {
   voteTxError = ''
   error = ''
 
+  mounted() {
```
Comment (samajammin) [inline vue-app/src/components/ContributionModal.vue:124]: I know this is somewhat outside the scope of this PR but should we also add a check to see if they've already approved (& move to step 2 if they have)? Or does that complicated things if their allowance is now different?

Comment (samajammin) [reply vue-app/src/components/ContributionModal.vue:124]: Ah, never mind, I see we already handle that 😄  https://github.com/ethereum/clrfund/blob/develop/vue-app/src/components/ContributionModal.vue#L159

File: vue-app/src/components/ContributionModal.vue [hunk 4]
```diff
@@ -118,10 +121,31 @@ export default class ContributionModal extends Vue {
...
+
   get currentRound(): RoundInfo {
     return this.$store.state.currentRound
   }
 
+  get signer(): Signer {
+    return this.$store.state.currentUser.walletProvider.getSigner()
+  }
+
+  get fundingRound(): Contract {
```
Comment (samajammin) [inline vue-app/src/components/ContributionModal.vue:144]: 👍

File: vue-app/src/router/index.ts [hunk 5]
```diff
@@ -183,7 +183,7 @@ const routes = [
     },
   },
   {
-    path: '/transaction-success/:type/:hash',
+    path: '/transaction-success/:type/:hash?',
```
Comment (samajammin) [inline vue-app/src/router/index.ts:186]: 👍

File: vue-app/src/store/index.ts [hunk 6]
```diff
@@ -147,6 +151,9 @@ export const mutations = {
   [SET_CONTRIBUTION](state, contribution: BigNumber | null) {
     state.contribution = contribution
   },
+  [SET_HAS_VOTED](state, hasVoted: boolean) {
```
Comment (samajammin) [inline vue-app/src/store/index.ts:154]: Perhaps `ADD_VOTE`?

Comment (samajammin) [reply vue-app/src/store/index.ts:154]: I'm actually fine with `SET_HAS_VOTED` as well.

Comment (samajammin) [reply vue-app/src/store/index.ts:154]: Ya because it could be `false` 👍

**Review by samajammin — APPROVED** [review]
Awesome work! 😍 

Personally I'd like to re-work the logic of the `canUserReallocate` getter but I also want to merge this so we can pull it into this next test round 😄

File: vue-app/src/router/index.ts (hunk 5 above)
Comment (pettinarip) [reply vue-app/src/router/index.ts:186]: Yes, I forgot to mention why I did this.

The reason is that when we are facing a partial contribution and the user refreshes the page, we lose that hash. So, for that case, I'm not showing any hash in the success screen.

File: vue-app/src/components/ContributionModal.vue (hunk 3 above)
Comment (pettinarip) [reply vue-app/src/components/ContributionModal.vue:124]: Uhmmm that's a good point. You are talking about #L180 right? where we have this condition:
```js
if (allowance < total) {
```

File: vue-app/src/components/Cart.vue (hunk 2 above)
Comment (pettinarip) [reply vue-app/src/components/Cart.vue:11]: Totally!

This is what I did in the first place.
```ts
canUserReallocate: (_, getters): boolean => {
  return (
    getters.hasUserContributed &&
    getters.hasUserVoted && // <--- to be able to reallocate, the user must vote first
    (getters.isRoundContributionPhase || getters.isRoundReallocationPhase)
  )
}
```

The problem I had with this approach (which I think is the best because it is clearer to future developers) is that the number of things I needed to change in the Cart UI logic was big and complex. Mainly because we want to display the same reallocation UI but with this flag off. There are a lot of conditions around `canUserReallocate`.

So, I'm keeping `canUserReallocate` truthy because it is easier from the refactoring perspective. I only needed to add a couple of conditions to the Cart logic using `hasUserVoted`.

I hate this because we are adding more and more conditions in the Cart logic what makes it super difficult to understand and maintain. I think this is a task we could tackle in the Technical Debt epic! :)

File: vue-app/src/store/index.ts (hunk 1 above)
Comment (pettinarip) [reply vue-app/src/store/index.ts:93]: Hmm yes. I didn't think of that. Makes total sense. I'm going to add myself a ticket into the Tech Debt epic to refactor this.

Comment (pettinarip) [reply vue-app/src/store/index.ts:93]: https://www.notion.so/efdn/Refactor-hasVoted-state-8b1fa27fa869410ba06baa248a7fb78e
