### PR TITLE
JoinLanding data fetching bug

### LINKED ISSUE #227: JoinLanding data fetching bug
https://www.notion.so/efdn/JoinLanding-data-fetching-bug-76b44882759542b3835d9b66f0e320d9

Something wacky is going on with our data fetching & rendering for this view.

If I load this page directly, e.g. opening a link:
https://eth2clrfund.netlify.app/#/join

No warning is displayed:
image

But if I navigate to a different page, then return I see this warning about the registry being almost full:
image

Let's investigate how we fetch this data & see if there's some issue e.g. if there's a race condition we're hitting.

**Note** - replicating this bug will require specific conditions (the MACI caps being almost full). - this can be mocked by updating the frontend values: https://github.com/ethereum/clrfund/blob/develop/vue-app/src/api/round.ts#L158

### PR DESCRIPTION
**Pull request by corwintines**
Notion: https://efdn.notion.site/JoinLanding-data-fetching-bug-76b44882759542b3835d9b66f0e320d9
Fixes: https://github.com/ethereum/clrfund/issues/227

Changes:
- Converted JoinLandings created lifecycle method into get methods since there was no good reason to keep the lifecycle method. Fixes any race condition that could have existed.

### CODE REVIEW

File: vue-app/src/views/JoinLanding.vue [hunk 1]
```diff
@@ -125,35 +125,35 @@ import BackToProjects from '../components/BackToProjects.vue'
...
-      this.recipientCount = this.registryInfo.recipientCount
-      this.deposit = this.registryInfo.deposit
-      this.depositToken = this.registryInfo.depositToken
-      this.spacesRemaining = maxRecipients - this.registryInfo.recipientCount
-    } catch (error) {
-      console.warn(error) /* eslint-disable-line no-console */
-    } finally {
-      this.isLoading = false
-    }
-  }
```
Comment (pettinarip) [inline vue-app/src/views/JoinLanding.vue:157]: 💯

File: contracts/scripts/deployTestRound.ts [hunk 2]
```diff
@@ -347,6 +347,95 @@ async function main() {
...
+    // recipient8Added.wait()
+
+    // const recipient8Id = await getEventArg(
+    //   recipient8Added,
+    //   recipientRegistry,
+    //   'RequestSubmitted',
+    //   '_recipientId'
+    // )
+    // const executeRequest8 = await recipientRegistry.executeRequest(recipient8Id)
+    // await executeRequest8.wait()
```
Comment (pettinarip) [inline contracts/scripts/deployTestRound.ts]: Maybe a bonus point for this (when we have the time) is to create a function outside this file that generates all these dummy data for us. Perhaps https://github.com/Marak/Faker.js could be useful for doing this.
```js
const recipientsData = fakeData.generateRecipients(10) // the amount of recipients you want
const recipients = recipientsData.map((recipient, index) => ({ account: accounts[index], metadata: recipient }))

// then add as many recipients as you want to the registry
const [ recipient1, recipient2 ] = recipients
addRecipientsToRegistry([ recipient1, recipient2 ]) // and this func does this repeated code
```
With this, we could make this file much shorter and cleaner.

**Review by pettinarip — APPROVED** [review]

File: contracts/scripts/deployTestRound.ts (hunk 2 above)
Comment (corwintines) [reply contracts/scripts/deployTestRound.ts]: Since we merged some different params into develop for maci params im just going to remove this. To test, you can just go into the vue store and play around with the currentRound

**Review by samajammin — APPROVED** [review]
👍
